### PR TITLE
Dgs3 gondar release imports

### PR DESCRIPTION
**Pull request by dgs3**
I couldn't find a requirements.txt file in here, so I figured we needed one.

### CODE REVIEW

**Comment by dgs3** [comment]
retest this please

**Comment by dgs3** [comment]
I have no idea why these tests are failing.  @kendase3  any idea?

**Comment by kendase3** [comment]
stderr: Cloning into 'gdisk'...
fatal: unable to access 'https://git.code.sf.net/p/gptfdisk/code/': GnuTLS recv error (-54): Error in the pull function.
fatal: clone of 'https://git.code.sf.net/p/gptfdisk/code' into submodule path 'gdisk' failed

**Comment by kendase3** [comment]
The gdisk submodule endpoint is down

**Pull request merged**
