### PR TITLE
Update text shown to user without network

### PR DESCRIPTION
**Pull request by kendase3**
Addresses OVER-5205

### CODE REVIEW

**Comment by nicholasbishop** [comment]
Is this change really accurate? There are a number of network conditions that might lead to this error, e.g. if we mess up permissions in AWS or there's an outage

**Comment by kendase3** [comment]
I actually had the ticket wrong; it's OVER-5205.  I'd @ one of the concerned parties there; I have no preference.  We could make a ticket to try hitting an endpoint likely to be up like neverware.com (no joeks plz).  If we can't hit the known-good endpoint, we could display this message; else display a message saying 'our bad' or similar.

**Comment by kendase3** [comment]
Imma push -f to update the "addresses".

**Comment by nicholasbishop** [comment]
Commented in JIRA

**Comment by kendase3** [comment]
i think this has been successfully 'why do we need this'd
closing for now

**Pull request closed without merging**
