### PR TITLE
Adjust device index by 130

### PR DESCRIPTION
**Pull request by kendase3**
DeviceGuy rework broke master for device index lookup.

### CODE REVIEW

**Comment by nicholasbishop** [comment]
I'm probably misunderstanding something about how these various indices and numbers are supposed to work. Could you sketch it out for me?

**Comment by kendase3** [comment]
The 130 is kind of explained by pbatard here https://github.com/neverware/gondar/blob/master/src/gondar.cc#L168

**Comment by kendase3** [comment]
Actually, it looks like the min is 128 (0x80).  So this change will only make things work on my machine :(

**Comment by nicholasbishop** [comment]
Oh! I see now that I misunderstood https://github.com/neverware/gondar/blob/b1ab2ddddb4876837cad46bda145be9e5e571e56/src/device.cc#L71

**Comment by nicholasbishop** [comment]
I will put up a PR for that shortly

**Comment by kendase3** [comment]
thx

**Pull request closed without merging**
